### ISSUE TITLE
Assignment 1 

### ISSUE THREAD

**Issue by traemalcolm** [VIS-2129-F2020/tmalcolm-vis#1]
[Assignment 1](file:///C:/Users/Taelor%20Malcolm/Documents/GitHub/tmalcolm-vis/Assignment-1.html)

**Comment by traemalcolm** [comment]
file:///C:/Users/Taelor%20Malcolm/Documents/GitHub/tmalcolm-vis/Assignment-1.html

**Comment by bauranov** [comment]
Testing
